name: example
description: Example for yet_another_decimal.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  ansi_escape_codes: ^2.0.3
  benchmark_harness: ^2.3.1
  big_decimal: ^0.5.0
  decimal: ^3.2.1
  decimal_type: ^0.0.2
  fixed: ^5.3.2
  format: ^1.6.0
  yet_another_decimal:
    path: ..

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

dependency_overrides:
  intl: 0.20.2
