name: yet_another_decimal
description: Yet another package for fixed point decimals.
version: 1.0.0
homepage: https://github.com/vi-k/yet_another_decimal

environment:
  sdk: ^3.6.0

dependencies:
  meta: ^1.16.0
  rational: ^2.2.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
